package main

import (
	"context"
	"fmt"
	"log"

	"net/http"

	"connectrpc.com/connect"
	"connectrpc.com/grpcreflect"
	hellov1 "github.com/tekam03/panierquebec-backend/gen/helloworld/v1"             // generated by protoc-gen-go
	"github.com/tekam03/panierquebec-backend/gen/helloworld/v1/helloworldv1connect" // generated by protoc-gen-connect-go
	"github.com/tekam03/panierquebec-backend/gen/stores/v1/storesv1connect"
	handlerMerchant "github.com/tekam03/panierquebec-backend/internal/handler/merchant"
	serviceMerchant "github.com/tekam03/panierquebec-backend/internal/service/merchant"
	repoMerchant "github.com/tekam03/panierquebec-backend/internal/repo/merchant"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"github.com/tekam03/panierquebec-backend/internal/config"
	"github.com/tekam03/panierquebec-backend/internal/db"
)

type HelloWorldServer struct{}

func (s *HelloWorldServer) Hello(
	ctx context.Context,
	req *connect.Request[hellov1.HelloRequest],
) (*connect.Response[hellov1.HelloResponse], error) {
	log.Println("Request headers: ", req.Header())

	var name string
	var url string
	err := db.Pool.QueryRow(ctx, `SELECT name, url FROM store_merchants`).Scan(&name, &url)

	if err != nil {
		log.Printf("Error querying database: %v", err)
		return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("failed to query database: %w", err))
	}
	log.Printf("Queried merchant: %s, URL: %s", name, url)
	res := connect.NewResponse(&hellov1.HelloResponse{
		Message: fmt.Sprintf("Hello, name :%s  url:%s", name, url),
	})
	res.Header().Set("HelloWorld-Version", "v1")
	return res, nil
}

func main() {
	config.LoadEnv()

	// Connect to the database
	if err := db.Connect(); err != nil {
		log.Fatalf("Could not connect to the database: %v", err)
	}
	defer db.Close()

	// test the merchant repository
	merchantRepo := repoMerchant.NewPostgresMerchantRepo()
	merchantService := serviceMerchant.NewService(merchantRepo)
	merchantHandler := handlerMerchant.NewMerchantHandler(merchantService)


	helloWorldGreeter := &HelloWorldServer{}
	mux := http.NewServeMux()
	path, handler := helloworldv1connect.NewHelloServiceHandler(helloWorldGreeter)
	mux.Handle(path, handler)
	path, handler = storesv1connect.NewMerchantServiceHandler(merchantHandler)
	mux.Handle(path, handler)
	reflector := grpcreflect.NewStaticReflector(
		helloworldv1connect.HelloServiceName,
		storesv1connect.MerchantServiceName,
	)
	// Many tools still expect the older version of the server reflection API, so
	// most servers should mount both handlers.
	mux.Handle(grpcreflect.NewHandlerV1(reflector))
	mux.Handle(grpcreflect.NewHandlerV1Alpha(reflector))
	// If you don't need to support HTTP/2 without TLS (h2c), you can drop
	// x/net/http2 and use http.ListenAndServeTLS instead.

	fmt.Println("Starting server on localhost:8080")
	server := &http.Server{
		Addr:    "localhost:8080",
		Handler: h2c.NewHandler(mux, &http2.Server{}),
		// Don't forget timeouts!
	}
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Failed to start server: %v", err)
	}

}
