package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	hellov1 "github.com/tekam03/panierquebec/gen/helloworld/v1" // generated by protoc-gen-go
	"github.com/tekam03/panierquebec/gen/helloworld/v1/helloworldv1connect" // generated by protoc-gen-connect-go
)

type HelloWorldServer struct{}

func (s *HelloWorldServer) Hello(
	ctx context.Context,
	req *connect.Request[hellov1.HelloRequest],
) (*connect.Response[hellov1.HelloResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&hellov1.HelloResponse{
		Message: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("HelloWorld-Version", "v1")
	return res, nil
}

func main() {
	helloWorldGreeter := &HelloWorldServer{}
	mux := http.NewServeMux()
	path, handler := helloworldv1connect.NewHelloServiceHandler(helloWorldGreeter)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
