package main

import (
	"context"
	"fmt"
	"log"

	// "net/http"

	"connectrpc.com/connect"
	// "golang.org/x/net/http2"
	// "golang.org/x/net/http2/h2c"
	hellov1 "github.com/tekam03/panierquebec-backend/gen/helloworld/v1" // generated by protoc-gen-go
	// "github.com/tekam03/panierquebec-backend/gen/helloworld/v1/helloworldv1connect" // generated by protoc-gen-connect-go

	"github.com/tekam03/panierquebec-backend/internal/config"
	"github.com/tekam03/panierquebec-backend/internal/db"
	"github.com/tekam03/panierquebec-backend/internal/repo"
)

type HelloWorldServer struct{}

func (s *HelloWorldServer) Hello(
	ctx context.Context,
	req *connect.Request[hellov1.HelloRequest],
) (*connect.Response[hellov1.HelloResponse], error) {
	log.Println("Request headers: ", req.Header())

	var name string
	var url string
	err := db.Pool.QueryRow(ctx, `SELECT name, url FROM store_merchants`).Scan(&name, &url)

	if err != nil {
		log.Printf("Error querying database: %v", err)
		return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("failed to query database: %w", err))
	}
	log.Printf("Queried merchant: %s, URL: %s", name, url)
	res := connect.NewResponse(&hellov1.HelloResponse{
		Message: fmt.Sprintf("Hello, name :%s  url:%s", name, url),
	})
	res.Header().Set("HelloWorld-Version", "v1")
	return res, nil
}

func main() {
	config.LoadEnv()

	// Connect to the database
	if err := db.Connect(); err != nil {
		log.Fatalf("Could not connect to the database: %v", err)
	}
	defer db.Close()


	// test the merchant repository
	merchantRepo := repo.NewMerchantRepo()
	merchants, err := merchantRepo.GetAllMerchants(context.Background())
	if err != nil {
		log.Fatalf("Could not get merchants: %v", err)
	}
	for _, merchant := range merchants {
		log.Printf("Merchant ID: %d, Name: %s, URL: %s", merchant.ID, merchant.Name, merchant.Url)
	}

	merch1, err := merchantRepo.GetMerchant(context.Background(), 1)
	if err != nil {
		log.Fatalf("Could not get merchant with ID 1: %v", err)
	}
	log.Printf("Merchant ID: %d, Name: %s, URL: %s", merch1.ID, merch1.Name, merch1.Url)


	// helloWorldGreeter := &HelloWorldServer{}
	// mux := http.NewServeMux()
	// path, handler := helloworldv1connect.NewHelloServiceHandler(helloWorldGreeter)
	// mux.Handle(path, handler)
	// fmt.Println("Starting server on localhost:8080")
	// http.ListenAndServe(
	// 	"localhost:8080",
	// 	// Use h2c so we can serve HTTP/2 without TLS.
	// 	h2c.NewHandler(mux, &http2.Server{}),
	// )
}
